{{- if .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "influxdb-pod.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "influxdb-pod.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "influxdb-pod.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow from specified namespaces
    {{- with .Values.networkPolicy.ingress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    # Allow from same namespace
    - from:
      - podSelector: {}
      ports:
        - protocol: TCP
          port: {{ .Values.influxdb.http.port }}
  egress:
    # Allow DNS
    - to:
      - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53
    # Custom egress rules
    {{- with .Values.networkPolicy.egress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
