{{- if .Values.networkPolicy.enabled }}
apiVersion: {{ include "node-exporter.networkPolicy.apiVersion" . }}
kind: NetworkPolicy
metadata:
  name: {{ include "node-exporter.fullname" . }}
  namespace: {{ include "node-exporter.namespace" . }}
  labels:
    {{- include "node-exporter.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "node-exporter.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  {{- with .Values.networkPolicy.ingress }}
  ingress:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
