apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "codesys-x86.fullname" . }}-config
  namespace: {{ include "codesys-x86.namespace" . }}
  labels:
    {{- include "codesys-x86.labels" . | nindent 4 }}
data:
  CODESYSControl.cfg: |
{{ .Values.config.codesysControl | indent 4 }}
  runtime.env: |
{{ .Values.config.runtimeEnv | indent 4 }}
