apiVersion: v1
kind: Service
metadata:
  name: {{ include "codesys-x86.fullname" . }}
  namespace: {{ include "codesys-x86.namespace" . }}
  labels:
    {{- include "codesys-x86.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "codesys-x86.selectorLabels" . | nindent 4 }}
  ports:
    - name: plc-comm
      port: {{ .Values.service.plc.port }}
      targetPort: {{ .Values.service.plc.targetPort }}
      protocol: {{ .Values.service.plc.protocol }}
      {{- if and (eq .Values.service.type "NodePort") .Values.service.plc.nodePort }}
      nodePort: {{ .Values.service.plc.nodePort }}
      {{- end }}
    - name: webvisu
      port: {{ .Values.service.webvisu.port }}
      targetPort: {{ .Values.service.webvisu.targetPort }}
      protocol: {{ .Values.service.webvisu.protocol }}
      {{- if and (eq .Values.service.type "NodePort") .Values.service.webvisu.nodePort }}
      nodePort: {{ .Values.service.webvisu.nodePort }}
      {{- end }}
    - name: opcua
      port: {{ .Values.service.opcua.port }}
      targetPort: {{ .Values.service.opcua.targetPort }}
      protocol: {{ .Values.service.opcua.protocol }}
      {{- if and (eq .Values.service.type "NodePort") .Values.service.opcua.nodePort }}
      nodePort: {{ .Values.service.opcua.nodePort }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "codesys-x86.fullname" . }}-headless
  namespace: {{ include "codesys-x86.namespace" . }}
  labels:
    {{- include "codesys-x86.labels" . | nindent 4 }}
    service-type: headless
spec:
  clusterIP: None
  selector:
    {{- include "codesys-x86.selectorLabels" . | nindent 4 }}
  ports:
    - name: plc-comm
      port: {{ .Values.service.plc.port }}
      targetPort: {{ .Values.service.plc.targetPort }}
      protocol: {{ .Values.service.plc.protocol }}
