{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "codesys-x86.serviceAccountName" . }}
  namespace: {{ include "codesys-x86.namespace" . }}
  labels:
    {{- include "codesys-x86.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
