{{- if and .Values.mqtt.persistence.enabled .Values.persistence.backup.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mosquitto.fullname" . }}-backup
  namespace: {{ include "mosquitto.namespace" . }}
  labels:
    {{- include "mosquitto.labels" . | nindent 4 }}
    app.kubernetes.io/component: backup
spec:
  accessModes:
    {{- toYaml .Values.persistence.backup.accessModes | nindent 4 }}
  {{- if .Values.persistence.backup.storageClass }}
  storageClassName: {{ .Values.persistence.backup.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.backup.size }}
{{- end }}
