apiVersion: v1
kind: Service
metadata:
  name: {{ include "mosquitto.fullname" . }}
  namespace: {{ include "mosquitto.namespace" . }}
  labels:
    {{- include "mosquitto.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ include "mosquitto.serviceType" . }}
  {{- if .Values.service.sessionAffinity }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  {{- if .Values.service.sessionAffinityConfig }}
  sessionAffinityConfig:
    {{- toYaml .Values.service.sessionAffinityConfig | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- if and (eq .Values.service.type "LoadBalancer") .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if and (eq .Values.service.type "LoadBalancer") .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml .Values.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  ports:
    {{- if .Values.mqtt.ports.mqtt.enabled }}
    - port: {{ .Values.mqtt.ports.mqtt.port }}
      targetPort: mqtt
      protocol: {{ .Values.mqtt.ports.mqtt.protocol }}
      name: mqtt
    {{- end }}
    {{- if .Values.mqtt.ports.mqtts.enabled }}
    - port: {{ .Values.mqtt.ports.mqtts.port }}
      targetPort: mqtts
      protocol: {{ .Values.mqtt.ports.mqtts.protocol }}
      name: mqtts
    {{- end }}
    {{- if .Values.mqtt.ports.websockets.enabled }}
    - port: {{ .Values.mqtt.ports.websockets.port }}
      targetPort: websockets
      protocol: {{ .Values.mqtt.ports.websockets.protocol }}
      name: websockets
    {{- end }}
    {{- if .Values.monitoring.enabled }}
    - port: {{ .Values.monitoring.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "mosquitto.selectorLabels" . | nindent 4 }}
