{{- if and .Values.web.enabled .Values.web.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "sqlite.fullname" . }}
  labels:
    {{- include "sqlite.labels" . | nindent 4 }}
  {{- with .Values.web.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.web.ingress.className }}
  ingressClassName: {{ .Values.web.ingress.className }}
  {{- end }}
  {{- if .Values.web.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.web.ingress.host }}
      secretName: {{ .Values.web.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.web.ingress.host }}
      http:
        paths:
          - path: {{ .Values.web.ingress.path }}
            pathType: {{ .Values.web.ingress.pathType }}
            backend:
              service:
                name: {{ include "sqlite.fullname" . }}
                port:
                  number: {{ .Values.web.service.port }}
{{- end }}
