{{- if and .Values.litestream.enabled .Values.litestream.s3.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sqlite.fullname" . }}-litestream
  labels:
    {{- include "sqlite.labels" . | nindent 4 }}
type: Opaque
stringData:
  accessKeyId: {{ .Values.litestream.s3.accessKeyId | quote }}
  secretAccessKey: {{ .Values.litestream.s3.secretAccessKey | quote }}
{{- end }}
