{{- if .Values.advanced.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sqlite.serviceAccountName" . }}
  labels:
    {{- include "sqlite.labels" . | nindent 4 }}
  {{- with .Values.advanced.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
