{{- if and .Values.customCerts.enabled (not .Values.customCerts.secretName) .Values.customCerts.cert .Values.customCerts.key }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sorba-sde.fullname" . }}-certs
  labels:
    {{- include "sorba-sde.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.customCerts.cert | b64enc }}
  tls.key: {{ .Values.customCerts.key | b64enc }}
{{- end }}
