apiVersion: v1
kind: Service
metadata:
  name: {{ include "sorba-sde.fullname" . }}
  labels:
    {{- include "sorba-sde.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpsPort }}
      targetPort: https
      protocol: TCP
      name: https
      {{- if and (eq .Values.service.type "NodePort") .Values.service.httpsNodePort }}
      nodePort: {{ .Values.service.httpsNodePort }}
      {{- end }}
    - port: {{ .Values.service.modbusPort }}
      targetPort: modbus
      protocol: TCP
      name: modbus
      {{- if and (eq .Values.service.type "NodePort") .Values.service.modbusNodePort }}
      nodePort: {{ .Values.service.modbusNodePort }}
      {{- end }}
    - port: {{ .Values.service.mqttPort }}
      targetPort: mqtt
      protocol: TCP
      name: mqtt
      {{- if and (eq .Values.service.type "NodePort") .Values.service.mqttNodePort }}
      nodePort: {{ .Values.service.mqttNodePort }}
      {{- end }}
    - port: {{ .Values.service.opcuaPort }}
      targetPort: opcua
      protocol: TCP
      name: opcua
      {{- if and (eq .Values.service.type "NodePort") .Values.service.opcuaNodePort }}
      nodePort: {{ .Values.service.opcuaNodePort }}
      {{- end }}
  selector:
    {{- include "sorba-sde.selectorLabels" . | nindent 4 }}
