{{- if and .Values.runtime.enabled .Values.runtime.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "codesys-runtime.runtime.serviceAccountName" . }}
  namespace: {{ include "codesys-runtime.namespace" . }}
  labels:
    {{- include "codesys-runtime.runtime.labels" . | nindent 4 }}
  {{- with .Values.runtime.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
