{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "codesys-edge-gateway.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "codesys-edge-gateway.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "codesys-edge-gateway.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  
  ingress:
    {{- with .Values.networkPolicy.ingress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  
  egress:
    {{- with .Values.networkPolicy.egress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
