{{- if not .Values.gateway.automationServer.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "codesys-edge-gateway.secretName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "codesys-edge-gateway.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.gateway.automationServer.username | default "admin" | quote }}
  password: {{ .Values.gateway.automationServer.password | default "changeme" | quote }}
{{- end }}
