{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "codesys-edge-gateway.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "codesys-edge-gateway.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "codesys-edge-gateway.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      path: {{ .Values.metrics.path }}
      interval: {{ .Values.metrics.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout }}
{{- end }}
