{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "telegraf.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "telegraf.labels" . | nindent 4 }}
  annotations:
    fireball.industries/high-availability: "enabled"
spec:
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "telegraf.selectorLabels" . | nindent 6 }}
{{- end }}
