{{- if and .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "telegraf.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "telegraf.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if eq .Values.deploymentMode "deployment" }}
  selector:
    {{- include "telegraf.selectorLabels" . | nindent 4 }}
  {{- end }}
  ports:
    {{- toYaml .Values.service.ports | nindent 4 }}
{{- end }}
