apiVersion: v2
name: grafana-loki
description: All-in-one observability solution
type: application
version: 1.0.0
appVersion: "10.2.3"
keywords:
  - grafana
  - loki
  - observability
home: https://github.com/fireball-industries/helm-charts
maintainers:
  - name: Patrick Ryan
    email: patrick@fireball-industries.com
annotations:
  catalog.cattle.io/certified: "partner"
  catalog.cattle.io/display-name: "Grafana + Loki Pod"
  catalog.cattle.io/release-name: "grafana-loki"
  catalog.cattle.io/namespace: "observability"
  catalog.cattle.io/categories: "Forge Industrial,Monitoring,Observability"
  catalog.cattle.io/os: "linux"
  catalog.cattle.io/type: "cluster-tool"