{{- if and (eq .Values.deploymentMode "ha") .Values.highAvailability.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "prometheus.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}
spec:
  {{- if .Values.highAvailability.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.highAvailability.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.highAvailability.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.highAvailability.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "prometheus.selectorLabels" . | nindent 6 }}
{{- end }}
