{{- if and .Values.license.activationKey (not .Values.license.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ignition-edge.fullname" . }}-license
  labels:
    {{- include "ignition-edge.labels" . | nindent 4 }}
type: Opaque
data:
  activation-key: {{ .Values.license.activationKey | b64enc | quote }}
  {{- if .Values.license.licenseFile }}
  license-file: {{ .Values.license.licenseFile | b64enc | quote }}
  {{- end }}
{{- end }}
