{{- if .Values.ingressClass.enabled }}
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: {{ .Values.ingressClass.name }}
  labels:
    {{- include "traefik.labels" . | nindent 4 }}
  {{- if .Values.ingressClass.isDefaultClass }}
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
  {{- end }}
spec:
  controller: traefik.io/ingress-controller
{{- end }}
