{{- if .Values.namespace.create -}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "node-red.namespace" . }}
  labels:
    {{- toYaml .Values.namespace.labels | nindent 4 }}
    {{- include "node-red.labels" . | nindent 4 }}
{{- end }}
