{{- if .Values.nodeRed.auth.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "node-red.secretName" . }}
  namespace: {{ include "node-red.namespace" . }}
  labels:
    {{- include "node-red.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.nodeRed.auth.username | quote }}
  password: {{ include "node-red.adminPassword" . | quote }}
{{- end }}
