{{- if .Values.pod.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "node-red.serviceAccountName" . }}
  namespace: {{ include "node-red.namespace" . }}
  labels:
    {{- include "node-red.labels" . | nindent 4 }}
  {{- with .Values.pod.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
