apiVersion: v1
kind: Secret
metadata:
  name: {{ include "n8n.fullname" . }}
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.config.basicAuth.enabled }}
  N8N_BASIC_AUTH_USER: {{ .Values.config.basicAuth.user | quote }}
  N8N_BASIC_AUTH_PASSWORD: {{ .Values.config.basicAuth.password | quote }}
  {{- end }}
  N8N_ENCRYPTION_KEY: {{ .Values.config.encryptionKey | quote }}
  {{- if eq .Values.database.type "postgres" }}
  {{- if .Values.database.postgres.external.enabled }}
  DB_TYPE: "postgresdb"
  DB_POSTGRESDB_HOST: {{ .Values.database.postgres.external.host | quote }}
  DB_POSTGRESDB_PORT: {{ .Values.database.postgres.external.port | quote }}
  DB_POSTGRESDB_DATABASE: {{ .Values.database.postgres.external.database | quote }}
  DB_POSTGRESDB_USER: {{ .Values.database.postgres.external.user | quote }}
  DB_POSTGRESDB_PASSWORD: {{ .Values.database.postgres.external.password | quote }}
  {{- end }}
  {{- end }}
